Add constraints and modify swagger config
beatakoziel/pizza-ordering-system pull request #7
Opened 2020-03-02 16:26 UTC by Haseoo

2020-03-02 18:08 UTC, beatakoziel requested changes

2020-03-02 18:08 UTC, beatakoziel commented on Slicesy.PizzaOrder.WebApi/Repositories/Models/Company.cs
> +        [StringLength(20, MinimumLength = 20, ErrorMessage = "Postal code must have {0} characters")]
postal code?

2020-03-02 18:12 UTC, Haseoo commented on Slicesy.PizzaOrder.WebApi/Repositories/Models/Company.cs
> +        [StringLength(20, MinimumLength = 20, ErrorMessage = "Postal code must have {0} characters")]
ups

2020-03-04 16:43 UTC, beatakoziel commented
Ok

2020-03-04 16:46 UTC, beatakoziel approved these changes

2020-03-04 16:46 UTC, merged